# Site settings
title: Matthew Thompson
email: matt@mattathompson.org
description: "Blog"
baseurl: ""
url: 
twitter_username: Mattyice_TYBG
github_username:  mattyice50

# Build settings
markdown: kramdown
permalink: pretty
